# Generated by Django 4.2.1 on 2024-10-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='../images/dog1.jpg', null=True, upload_to=''),
        ),
    ]
